#!/usr/bin/env python3
"""paper-reproducer inference WebUI (generic, config-driven).

This file is a fixed template copied verbatim from
paper-reproduce-skills/templates/webui/app.py — it contains **no
repo-specific logic**. Everything specific to the reproduced repository
lives in `webui.json` next to this file, generated by the webui-builder
skill (schema: paper-reproduce-skills/schemas/webui.schema.json).

Design (CLI wrapper): each request runs the Phase-3-verified inference
command via subprocess inside the reproduced repo's pixi environment.
The model is reloaded per request — slower than a resident model, but it
works for arbitrary repos because the exact command already succeeded.

Usage:
    pixi run python app.py [--config webui.json] [--port 7860] [--smoke]
"""

import argparse
import datetime as _dt
import json
import os
import shlex
import shutil
import string
import subprocess
import sys
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent

INPUT_TYPES = ("image", "video", "file", "files", "text")
OUTPUT_TYPES = ("image", "gallery", "video", "model3d", "file")


# --------------------------------------------------------------------------
# Pure helpers (no gradio import; covered by tests/test_webui_app.py)
# --------------------------------------------------------------------------

def template_placeholders(template: str) -> set:
    """Return the set of `{name}` placeholders in a command template."""
    return {
        field for _, field, _, _ in string.Formatter().parse(template)
        if field is not None and field != ""
    }


def load_config(path: Path) -> dict:
    """Load and validate webui.json. Raise ValueError on structural problems.

    Validation here is a runtime guard for hand-edited configs; the
    authoritative shape check is `check-jsonschema` against
    schemas/webui.schema.json at generation time.
    """
    with open(path, encoding="utf-8") as f:
        cfg = json.load(f)

    for key in ("title", "workdir", "command_template", "inputs", "outputs"):
        if key not in cfg:
            raise ValueError(f"webui.json: missing required key '{key}'")
    if not cfg["outputs"]:
        raise ValueError("webui.json: 'outputs' must have at least one entry")

    input_names = set()
    for spec in cfg["inputs"]:
        for key in ("name", "type", "label"):
            if key not in spec:
                raise ValueError(f"webui.json: input entry missing '{key}': {spec}")
        if spec["type"] not in INPUT_TYPES:
            raise ValueError(f"webui.json: unknown input type '{spec['type']}'")
        if spec["name"] in input_names:
            raise ValueError(f"webui.json: duplicate input name '{spec['name']}'")
        input_names.add(spec["name"])

    for spec in cfg["outputs"]:
        if "glob" not in spec or "type" not in spec:
            raise ValueError(f"webui.json: output entry missing 'glob'/'type': {spec}")
        if spec["type"] not in OUTPUT_TYPES:
            raise ValueError(f"webui.json: unknown output type '{spec['type']}'")

    placeholders = template_placeholders(cfg["command_template"])
    unknown = placeholders - input_names - {"output_dir"}
    if unknown:
        raise ValueError(
            f"webui.json: command_template placeholders {sorted(unknown)} "
            f"have no matching input entry"
        )

    cfg.setdefault("description", "")
    cfg.setdefault("timeout_s", 3600)
    cfg.setdefault("example_input", None)
    cfg["_uses_output_dir"] = "output_dir" in placeholders
    return cfg


def build_command(template: str, values: dict) -> str:
    """Substitute `{name}` placeholders with shell-quoted values."""
    quoted = {k: shlex.quote(str(v)) for k, v in values.items()}
    return template.format(**quoted)


def collect_outputs(cfg: dict, output_dir: Path, started_at: float) -> dict:
    """Collect produced files per output spec.

    If the command template used `{output_dir}`, globs are resolved inside
    the per-job output dir. Otherwise the repo writes to fixed paths, so
    globs are resolved against workdir and filtered to files modified
    after the job started (1s slack for coarse filesystem mtimes).
    """
    base = output_dir if cfg["_uses_output_dir"] else Path(cfg["workdir"])
    collected = {}
    for i, spec in enumerate(cfg["outputs"]):
        matches = sorted(base.glob(spec["glob"]))
        if not cfg["_uses_output_dir"]:
            matches = [p for p in matches if p.stat().st_mtime >= started_at - 1.0]
        collected[i] = [p for p in matches if p.is_file()]
    return collected


def run_job(cfg: dict, input_values: dict, jobs_root: Path) -> tuple:
    """Run one inference job. Returns (log_text, {output_index: [Path, ...]})."""
    job_dir = jobs_root / _dt.datetime.now().strftime("%Y%m%d-%H%M%S-%f")
    output_dir = job_dir / "output"
    output_dir.mkdir(parents=True, exist_ok=True)

    values = dict(input_values)
    if cfg["_uses_output_dir"]:
        values["output_dir"] = str(output_dir)
    cmd = build_command(cfg["command_template"], values)

    started_at = _dt.datetime.now().timestamp()
    log_lines = [f"$ {cmd}", f"(cwd: {cfg['workdir']})", ""]
    try:
        proc = subprocess.run(
            cmd,
            shell=True,
            cwd=cfg["workdir"],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=cfg["timeout_s"],
            text=True,
            errors="replace",
            env={**os.environ, "PYTHONUNBUFFERED": "1"},
        )
        log_lines.append(proc.stdout or "")
        log_lines.append(f"[exit code: {proc.returncode}]")
        ok = proc.returncode == 0
    except subprocess.TimeoutExpired as e:
        log_lines.append(e.stdout or "")
        log_lines.append(f"[timed out after {cfg['timeout_s']}s]")
        ok = False

    outputs = collect_outputs(cfg, output_dir, started_at) if ok else {}
    if ok and not any(outputs.values()):
        log_lines.append(
            "[warning: command succeeded but no output file matched the "
            "configured globs — check webui.json outputs[].glob]"
        )
    return "\n".join(log_lines), outputs


def stage_inputs(cfg: dict, raw_values: list, job_inputs_dir: Path) -> dict:
    """Normalize gradio component values into template placeholder values.

    - text        -> the string as-is
    - image/video/file -> filepath string handed over by gradio
    - files       -> the uploaded files are copied into one directory and
                     the placeholder value becomes that directory's path
                     (multi-view / multi-frame repos take an input dir)
    """
    values = {}
    for spec, raw in zip(cfg["inputs"], raw_values):
        if raw is None or raw == "":
            raise ValueError(f"input '{spec['label']}' is required")
        if spec["type"] == "text":
            values[spec["name"]] = str(raw)
        elif spec["type"] == "files":
            dest = job_inputs_dir / spec["name"]
            dest.mkdir(parents=True, exist_ok=True)
            for item in raw:
                src = Path(getattr(item, "name", item))
                shutil.copy(src, dest / src.name)
            values[spec["name"]] = str(dest)
        else:
            values[spec["name"]] = str(getattr(raw, "name", raw))
    return values


# --------------------------------------------------------------------------
# Gradio UI (imported lazily so pure helpers stay testable without gradio)
# --------------------------------------------------------------------------

def build_ui(cfg: dict, jobs_root: Path):
    import gradio as gr

    def _input_component(spec):
        if spec["type"] == "image":
            return gr.Image(label=spec["label"], type="filepath")
        if spec["type"] == "video":
            return gr.Video(label=spec["label"])
        if spec["type"] == "files":
            return gr.Files(label=spec["label"])
        if spec["type"] == "text":
            return gr.Textbox(label=spec["label"], value=spec.get("default") or "")
        return gr.File(label=spec["label"])

    def _output_component(spec):
        label = spec.get("label", spec["type"])
        if spec["type"] == "gallery":
            return gr.Gallery(label=label)
        if spec["type"] == "image":
            return gr.Image(label=label)
        if spec["type"] == "video":
            return gr.Video(label=label)
        if spec["type"] == "model3d":
            return gr.Model3D(label=label)
        return gr.Files(label=label)

    def _to_component_value(spec, paths):
        if not paths:
            return None
        strs = [str(p) for p in paths]
        if spec["type"] == "gallery":
            return strs
        if spec["type"] == "file":
            return strs
        return strs[0]

    def _run(*raw_values):
        job_inputs = jobs_root / "_staging" / _dt.datetime.now().strftime("%Y%m%d-%H%M%S-%f")
        try:
            values = stage_inputs(cfg, list(raw_values), job_inputs)
        except ValueError as e:
            raise gr.Error(str(e))
        log, outputs = run_job(cfg, values, jobs_root)
        return [log] + [
            _to_component_value(spec, outputs.get(i, []))
            for i, spec in enumerate(cfg["outputs"])
        ]

    with gr.Blocks(title=cfg["title"]) as demo:
        gr.Markdown(f"# {cfg['title']}")
        if cfg["description"]:
            gr.Markdown(cfg["description"])
        with gr.Row():
            with gr.Column():
                in_components = [_input_component(s) for s in cfg["inputs"]]
                run_btn = gr.Button("Run inference", variant="primary")
            with gr.Column():
                out_components = [_output_component(s) for s in cfg["outputs"]]
                log_box = gr.Textbox(label="Log", lines=14, max_lines=30)
        example = cfg["example_input"]
        if example and len(in_components) == 1 and cfg["inputs"][0]["type"] != "files":
            example_path = Path(cfg["workdir"]) / example
            if example_path.is_file():
                gr.Examples(examples=[[str(example_path)]], inputs=in_components)
        run_btn.click(_run, inputs=in_components, outputs=[log_box] + out_components)

    demo.queue(default_concurrency_limit=1)  # one job at a time on the GPU
    return demo


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=APP_DIR / "webui.json")
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int,
                        default=int(os.environ.get("WEBUI_PORT", "7860")))
    parser.add_argument("--smoke", action="store_true",
                        help="launch, wait until HTTP 200, then exit (CI/smoke test)")
    args = parser.parse_args()

    cfg = load_config(args.config)
    jobs_root = APP_DIR / "jobs"
    jobs_root.mkdir(exist_ok=True)

    demo = build_ui(cfg, jobs_root)
    allowed = [str(APP_DIR), cfg["workdir"]]
    demo.launch(
        server_name=args.host,
        server_port=args.port,
        show_error=True,
        share=False,
        allowed_paths=allowed,
        prevent_thread_lock=args.smoke,
        quiet=args.smoke,
    )

    if args.smoke:
        import time
        import urllib.request
        url = f"http://127.0.0.1:{args.port}/"
        for _ in range(30):
            try:
                with urllib.request.urlopen(url, timeout=2) as resp:
                    if resp.status == 200:
                        print(f"SMOKE OK: {url} -> 200")
                        demo.close()
                        return 0
            except Exception:
                time.sleep(2)
        print(f"SMOKE FAILED: {url} unreachable", file=sys.stderr)
        demo.close()
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
